model_list:
  - model_name: bedrock/sonnet-4.6
    litellm_params:
      drop_params: true
      model: "os.environ/AWS_SONNET_4_6_PROFILE"
      aws_region_name: "os.environ/AWS_REGION_NAME"
      aws_access_key_id: "os.environ/AWS_ACCESS_KEY_ID"
      aws_secret_access_key: "os.environ/AWS_SECRET_ACCESS_KEY"
